### ISSUE TITLE
Backport to main repo?

### ISSUE THREAD

**Issue by jezdez** [NZME/django-constance-cli#2]
Hey @therefromhere, this feature looks useful for the main repo, mind contributing it back?

**Comment by therefromhere** [comment]
Yep no problem, I was meaning to suggest this :)

**Comment by therefromhere** [comment]
@jezdez there's an updated PR on django-constance if you could review + merge it.

**Comment by therefromhere** [comment]
Note to other readers, the backported functionality is part of django-constance>=1.3.4 , see http://django-constance.readthedocs.io/en/latest/#command-line
